var categories = [
  'Crime',
  'Democracy',
  'Economy',
  'Education',
  'Energy',
  'Environment',
  'EU',
  'Health',
  'Immigration',
  'Military',
  'Pensions',
  'Private-Intervention',
  'Private/Public',
  'Rights',
  'State/Local',
  'Surveillance',
  'Tax',
  'Transport',
  'Unions',
  'Welfare'
];
var categoryMap = {
  'Abortion, Embryology and Euthanasia- Against':	'Health',
  'Academy Schools - for' :	'Education',
  'Action to prevent domestic violence' :	'Crime',
  'Additional Rate of Income Tax - Increase' :	'Tax',
  'Against On-Shore Wind Turbines' :	'Environment',
  'Apprenticeships' :	'Private-Intervention',
  'Assisted Dying' :	'Health',
  'Asylum System - More strict' :	'Immigration',
  'Balance the Budget Without Borrowing' :	'Economy',
  'Ban fox hunting' :	'Environment',
  'Bankers\' Bonus Tax' :	'Tax',
  'Business and community control of schools: For' :	'Private/Public',
  'Cap or Reduce Civil Service Redundancy Payments' :	'Welfare',
  'Civil aviation pollution - For limiting' :	'Environment',
  'Closed Material Proceedure' :	'Crime',
  'Coalition Programme for Government - For' :	'Democracy',
  'Control Orders' :	'Crime',
  'Corporal punishment of children - Against' :	'Crime',
  'Crossrail - In favour' :	'Transport',
  'Cull Badgers' :	'Environment',
  'Deployment of UK armed forces in Afghanistan' :	'Military',
  'Do more to help refugees inclding children' :	'Immigration',
  'Employee Shareholder Status' :	'Rights',
  'Encourage and incentivise saving' :	'Economy',
  'End support for some 16-18 yr olds in education' :	'Welfare',
  'Energy Prices - More Affordable' :	'Private-Intervention',
  'English Votes on English Laws etc.' :	'Democracy',
  'Equal Number of Electors Per Constituency - for' :	'Democracy',
  'European Union - For' :	'EU',
  'Excess Bedroom Benefit Penalty for Social Tenants' :	'Welfare',
  'Extend Right to Buy to Housing Associations' :	'Private/Public',
  'Fixed Term Parliaments' :	'Democracy',
  'For the UK to Remain a Member of the EU' :	'EU',
  'Foundation hospitals - In favour' :	'Health',
  'Fox hunting - Ban' :	'Environment',
  'Freedom of Information Bill 2000 - Strengthen' :	'Rights',
  'Fully Elected House of Lords' :	'Democracy',
  'Further Devolution to Scotland' :	'Democracy',
  'Further devolution to Wales' :	'Democracy',
  'Gambling - Against permissiveness' :	'Private-Intervention',
  'GP Commissioning in the NHS' :	'Health',
  'Higher Pay for Public Sector Workers' :	'Tax',
  'Higher taxes on alcoholic drinks' :	'Tax',
  'Higher taxes on banks' :	'Tax',
  'Higher taxes on sugary drinks' :	'Tax',
  'Hold a UK referendum on Lisbon EU Treaty' :	'EU',
  'Homosexuality - Equal rights' :	'Rights',
  'HS2 - In Favour' :	'Transport',
  'Human Rights and Equality' :	'Rights',
  'Identity cards - For introduction' :	'Surveillance',
  'In Favour of Mass Surveillance' :	'Surveillance',
  'Incentivise Low Carbon Electricity Generation' :	'Environment',
  'Incentivise membership of press regulator' :	'Private-Intervention',
  'Increase Air Passenger Duty' :	'Private-Intervention',
  'Increase the income tax - tax free allowance' :	'Tax',
  'Increase VAT' :	'Tax',
  'Inheritance Tax' :	'Tax',
  'Iraq 2003 - For the invasion' :	'Military',
  'Iraq Investigation - Necessary' :	'Military',
  'Jobs Guarantee for Long Term Young Unemployed' :	'Private-Intervention',
  'Limit NHS Foundation Trust Private Patient Income' :	'Health',
  'Localise Council Tax Support' :	'Tax',
  'Lower taxes on petrol & diesel for motor vehicles' :	'Tax',
  'Make High Earners Pay Market Rent for Council Home' :	'Private/Public',
  'Make it easier to trigger a new election for an MP' :	'Democracy',
  'Mansion Tax' :	'Tax',
  'Mass Retention of Communications Data' :	'Surveillance',
  'Measures to reduce tax avoidance.' :	'Tax',
  'Member trustees on pension boards' :	'Pensions',
  'Merge Police and Fire under Police & Crime Cmmr' :	'Crime',
  'Military Action against Daesh / ISIL' :	'Military',
  'Ministers Can Intervene in Coroners\' Inquests' :	'Crime',
  'Minumum Wage' :	'Private-Intervention',
  'More Emergency Service Workers' :	'Welfare',
  'More funds for social care' :	'Welfare',
  'More Generous Benefits for Ill and Disabled' :	'Welfare',
  'More powers for local councils' :	'State/Local',
  'No detention without charge or trial' :	'Crime',
  'No Polls Clash With MP Election System Referendum' :	'Democracy',
  'Nuclear power - For' :	'Energy',
  'Parliamentary scrutiny - Reduce' :	'Democracy',
  'Pension auto-enrolment - For' :	'Pensions',
  'Phase out of Tenancies for Life' :	'Private/Public',
  'Police and Crime Commissioners' :	'Crime',
  'Post office - in favour of Government policy' :	'Private/Public',
  'Post office closures - against' :	'Private/Public',
  'Prevent abuse of zero hours contracts' :	'Private-Intervention',
  'Privatise Royal Mail' :	'Private/Public',
  'Promote Occupational Pensions' :	'Private-Intervention',
  'Proportional Representation Voting System - For' :	'Democracy',
  'Protesting near Parliament - Unrestricted' :	'Democracy',
  'Public Ownership of Railways' :	'Private/Public',
  'Rail Fares - Lower' :	'Private/Public',
  'Recreational drugs - Against legalization' :	'Health',
  'Reduce capital gains tax' :	'Tax',
  'Reduce central funding for local government' :	'State/Local',
  'Reduce Spending on Welfare Benefits' :	'Welfare',
  'Reduce the rate of Corporation Tax' :	'Tax',
  'Reducing the number of MPs - for' :	'Democracy',
  'Referendum on Alternative Vote for MP Elections' :	'Democracy',
  'Referendum on the UK\'s membership of the EU - For' :	'EU',
  'Referendums for Directly Elected City Mayors' :	'Democracy',
  'Register of Lobbyists' :	'Democracy',
  'Regulation of Shale Gas Extraction' :	'Energy',
  'Remove Hereditary Peers from the House of Lords' :	'Democracy',
  'Replace Higher Education Grants with Loans' :	'Education',
  'Require Pub Companies to Offer Rent Only Leases' :	'Private-Intervention',
  'Restrict 3rd party campaigners during elections' :	'Democracy',
  'Restrict Scope of Legal Aid' :	'Crime',
  'Retain funds from council house sales locally' :	'State/Local',
  'Retention of Business Rates by Local Government' :	'State/Local',
  'Right for EU Citizens in the UK to Stay' :	'Immigration',
  'Right to strike' :	'Unions',
  'Same Sex Marriage - for' :	'Rights',
  'Schools - Greater Autonomy' :	'State/Local',
  'Sell England\'s Public Forests' :	'Private/Public',
  'Smoking ban - In favour' :	'Health',
  'State control of bus services' :	'Private/Public',
  'Stop climate change' :	'Environment',
  'Stronger Military Covenant' :	'Military',
  'Tax Incentives for Companies Investing in Assets' :	'Tax',
  'Teach children about drugs, sexuality and health' :	'Education',
  'Termination of pregnancy - against' :	'Health',
  'Terrorism laws - For' :	'Crime',
  'The UK should not ratify the Lisbon Treaty' :	'EU',
  'Tougher on illegal immigration' :	'Immigration',
  'Trade Union Regulation' :	'Unions',
  'Transexuality - Against legal recognition' :	'Rights',
  'Transparency of Parliament' :	'Rights',
  'Trident replacement - In favour' :	'Military',
  'Tuition fees - Set Upper Limit at £9,000 per Year' :	'Education',
  'University education fees - Should be free' :	'Education',
  'University Tuition Fees - For' :	'Education',
  'Use of UK Military Forces Overseas' :	'Military',
  'Voting age - Reduce to 16' :	'Democracy',
  'War - Parliamentary authority not necessary' :	'Military',
  'Welfare benefits ought rise in line with prices' :	'Welfare'
};
